/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>

using namespace std;

#define forn(i, n) for(int i = 0 ; (i) < (n) ; ++i)
#define forx(i, n) for(int i = 1 ; (i) <= (n) ; ++i)
#define ll long long
#define all(x) (x).begin(),(x).end()
#define sqr(x) (x) * (x)
#define debug(x) cout << #x <<" = " << x << endl
#define printvpair(v) for(auto x : v) cout << x.first  <<" " << x.second << endl;
#define printv(v) if (v.size()> 0) {for(auto x : v) cout << x << " "; cout << endl;}
#define MINUS(a) memset(a,0xff,sizeof(a))

const int N = 1e5 + 7;

const int dx[4] = {0, 0, 1, -1};
const int dy[4] = {1, -1, 0, 0};


class CountTheFactors {
public:
    void solve(std::istream &cin, std::ostream &cout) {
        int n;
        while (cin >> n) {
            int t = n;
            if (n == 0) {
                break;
            }
            int i = 2;
            set<int> ans;

            while (i * i <= n) {

                while (n % i == 0) {
                    ans.insert(i);
                    n /= i;
                }

                i++;
            }

            if (n > 1) {
                ans.insert(n);
            }

            cout << t << " : " << ans.size() << endl;
        }
    }
};


int main() {
    CountTheFactors solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}